# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('age_restricted', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('persons', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('stage_theatre', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('price', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255)),
                ('phones', models.CharField(blank=True, max_length=255)),
                ('work_time_kassa', models.CharField(blank=True, max_length=255)),
                ('work_time_openhours', models.CharField(blank=True, max_length=255)),
                ('metros', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('timetill', models.CharField(blank=True, max_length=10, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Place')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', through='events.Schedule', to='events.Place'),
        ),
    ]
